### ISSUE TITLE
DataManager 폴더변경에 의한 folder_data 변경안되는 문제

### ISSUE THREAD

**Issue by bh91034** [Carrer-Bootcamps/OpenCV-OCR-Translate#15]
폴더 변경시, clicked_change_folder() 가 불려지고, 
그 callback 함수 안에서 DataManager.reset_work_folder(dir_path) 을 부르는데요.
실제 DataManager.reset_work_folder(dir_path) 함수를 가보면,

    @classmethod
    def reset_work_folder(cls, target_folder='./image'):
        print ('[DataManager.reset] reset, target=', target_folder)
        cls.target_folder = os.path.abspath(target_folder)
 
위와 같이 되어있어요.

이렇게 해서는 변경된 폴더의 내용이 update 되지 않습니다.
최종적으로 DataManager 의 folder_data 가 새로 변경된 폴더의 내용으로 전체가 변경되어 있어야 하는데, 그게 지금 안되고 있는데요.
확인하고 수정 해 주세요.

**Comment by JiwonHwang84** [comment]
제가 생성한 이전 이슈와 동일한 이슈로, 현재는 수정하여 윤정님께 리뷰확인중입니다!

**Comment by bh91034** [comment]
네, 이해했습니다.

Duplicate:
https://github.com/Career-Bootcamps/OpenCV-OCR-Translate/issues/9
