### ISSUE TITLE
프로그램 실행 후 __OUTPUT_FILES__ 생성으로 git status 에 영향을 줌

### ISSUE THREAD

**Issue by bh91034** [Carrer-Bootcamps/OpenCV-OCR-Translate#23]
프로그램을 한번 실행하고 나면 __OUTPUT_FILES__ 아래 4개의 file 이 생성되므로, 이렇게 생성된 파일들이 git status 에 영향을 주지 않도록 .gitignore 파일에 추가해 주어야 함

**Comment by JiwonHwang84** [comment]
현재 프로젝트 안 __OUTPUT_FILES__/ 폴더 안 이미지와 
(사용자가 변경하는) 폴더 "image"폴더 안  __OUTPUT_FILES__/ 이미지를 무시하도록 gitinore파일을 수정하였습니다.
한가지 궁금한점은 다른 폴더 명일경우 해당  __OUTPUT_FILES__/  이미지는 무시되지 않을 것 같은데 이럴때는 경로를 어떻게 줘야하는지 궁금합니다.

**Comment by bh91034** [comment]
지원님의 ignore-output-files 브렌치를 기준으로, 아래와 같은 내용을 넣으셨어요.
__OUTPUT_FILES__/*.jpg
image/__OUTPUT_FILES__/*.jpg

만약, 내가 원하는 것이 repository 안에 어디가 되었든 __OUTPUT_FILES__ 라는 폴더 자체를 무시하도록 하고 싶다면, 그냥 아래 한줄이면 충분합니다.
__OUTPUT_FILES__/

repository 아래의 여기저기에 폴더를 copy 해보시면 이해하는데 도움이 될 것 같습니다.
