### ISSUE TITLE
편집 tab UI layout 구현

### ISSUE THREAD

**Issue by JuyeongKime2** [Carrer-Bootcamps/OpenCV-OCR-Translate#35]
편집 탭 디자인 구현

**Comment by JuyeongKime2** [comment]
![image](https://github.com/user-attachments/assets/faab5687-e1e0-4c10-9f1f-2860a9195373)

밝기, 대비조절 UI는 슬라이더로 구현하였습니다. 양 옆에 배치시키고 슬라이더바를 중앙에 배치시켜 -50부터 50까지의 값을 주었습니다.

**Comment by JuyeongKime2** [comment]
lowframe 에서 subframes 로 이동 후 ui 생성 코드  구현완료하였습니다

**Comment by bh91034** [comment]
Merge 된 이후에 close 해주세요..

**Comment by JuyeongKime2** [comment]
Merge 완료하여 close 하겠습니다

**Comment by JuyeongKime2** [comment]
![image](https://github.com/user-attachments/assets/33697cbf-8220-470f-a443-3f7a1b1c3c90)
브랜치 변경 후 다시 슬라이더 UI 생성완료했습니다
