### ISSUE TITLE
top - 이전이미지 버튼과 기능 구현

### ISSUE THREAD

**Issue by eunseoJeong** [Carrer-Bootcamps/OpenCV-OCR-Translate#8]
## 기능
- 폴더 이전 이미지로 이동하는 버튼 및 기능 구현
- 단, 마지막 이미지에서는 경고 팝업창 띄워야 함

**Comment by JiwonHwang84** [comment]
버튼클릭시 이미지 넘어가는게 안보이는데, 버튼만 구현하신 걸까요?

**Comment by JiwonHwang84** [comment]
넵 수정결과 확인했습니다!
